# Generated by Django 6.0.3 on 2026-03-30 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='Valeur',
            new_name='valeur',
        ),
    ]
